---
pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - script: ln -s "$(pwd)" ../ansible_role_pipenv
    displayName: Alias checkout directory for Molecule
  - script: ./moleculew wrapper-install
    displayName: Install molecule
  - script: ./moleculew test
    displayName: Run molecule tests
